In [12]:
import pandas as pd
from sklearn.metrics import mean_squared_error,confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [13]:
df=pd.read_csv('fish.csv')
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [14]:
x=df[['Weight','Length1','Length2','Length3','Height','Width']]
y=df["Species"]

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [16]:
nn=KNeighborsClassifier(n_neighbors=11)

In [18]:
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.59375

In [19]:
print(confusion_matrix(y_test,y_pred))

[[7 0 3 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 6 0 3 0 0]
 [1 0 1 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 5 0]
 [0 0 3 0 0 0 0]]

## Prog 2

In [20]:
# weight=85,le1=25.0,le2=20.0,le3=31,hei=6.0,width=2.5
print(model.predict([[85,25,20,31,6,2.5]]))

['Perch']

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [21]:
df=pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Column1,Column2
0,1,5.1,3.5,1.4,0.2,Iris-setosa,NaN,NaN
1,2,4.9,3.0,1.4,0.2,Iris-setosa,NaN,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa,NaN,NaN
3,4,4.6,3.1,1.5,0.2,Iris-setosa,NaN,NaN
4,5,5.0,3.6,1.4,0.2,Iris-setosa,NaN,NaN
...,...,...,...,...,...,...,...,...
95,96,5.7,3.0,4.2,1.2,Iris-versicolor,NaN,NaN
96,97,5.7,2.9,4.2,1.3,Iris-versicolor,NaN,NaN
97,98,6.2,2.9,4.3,1.3,Iris-versicolor,NaN,NaN
98,99,5.1,2.5,3.0,1.1,Iris-versicolor,NaN,NaN
99,100,5.7,2.8,4.1,1.3,Iris-versicolor,NaN,NaN

In [24]:
x=df[['SepalLengthCm',"SepalWidthCm",'PetalLengthCm','PetalWidthCm']]
y=df['Species']

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [26]:
nn=KNeighborsClassifier(n_neighbors=50)
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))

1.0

In [27]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]