In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
df=pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
x=df[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]
y=df['Outcome']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4)

In [9]:
x_train.shape

(614, 8)

In [10]:
nn=KNeighborsClassifier(n_neighbors=25)

In [12]:
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("Accuracy score=",accuracy_score(y_test,y_pred))  #// jya true aavtu hoy tya pred sachu hoy
cm=confusion_matrix(y_test,y_pred)
cm

Accuracy score= 0.7597402597402597

array([[90, 12],
       [25, 27]])

In [13]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [15]:
ACCURACY=(TN+TP)/(TP+TN+FP+FN)
ERRORRATE=FP+FN/TP+TN+FP+FN
SENSITIVITY=TP/TP+FN
SPACIFICITY=TN/TN+FP

In [16]:
print("Accuracy:",ACCURACY)
print("ERRORRATE",ERRORRATE)
print("SENSITIVITY",SENSITIVITY)
print("SPACIFICITY",SPACIFICITY)

Accuracy: 0.7597402597402597
ERRORRATE 139.92592592592592
SENSITIVITY 26.0
SPACIFICITY 13.0

In [18]:
# preg=4,glucose 95,blood pressure=55 skinthickness=30, insuline=180 , body mass index=BMI=29,DiabetedPRedifr=0.5 AGE=51
predictef=model.predict([[4,95,55,30,180,29,0.5,51]])
predictef

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

## <font color='red'>PROGRAM=2</font>

In [42]:
import pandas as pd
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,accuracy_score,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [43]:
df=pd.read_csv("data_breast_cancer.csv")
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [44]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [45]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [46]:
y=df['diagnosis']
x=df[[ 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
x_test.shape

(114, 30)

In [49]:
nn=KNeighborsClassifier(n_neighbors=22)
nn

KNeighborsClassifier(n_neighbors=22)

In [50]:
model=nn.fit(x_train,y_train)
jesse=model.predict(x_test)
jesse

array(['B', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M'], dtype=object)

In [54]:
print("Accuracy score=",accuracy_score(y_test,jesse)) 
cm=confusion_matrix(y_test,jesse)
cm

Accuracy score= 0.956140350877193

array([[71,  0],
       [ 5, 38]])

In [56]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [57]:
ACCURACY=(TN+TP)/(TP+TN+FP+FN)
ERRORRATE=FP+FN/TP+TN+FP+FN
SENSITIVITY=TP/TP+FN
SPACIFICITY=TN/TN+FP

In [58]:
print(ACCURACY)
print(ERRORRATE)
print(SENSITIVITY)
print(SPACIFICITY)

0.956140350877193
76.13157894736842
6.0
1.0

## <font color='green'>PROGRAM=3</font>

In [60]:
df=pd.read_csv("PlayTennis.csv")
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [61]:
df=pd.get_dummies(data=df,drop_first=True)
df.head()

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True

In [62]:
df.columns

Index(['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal', 'play_yes'],
      dtype='object')

In [63]:
x=df[['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal',]]
y=df['play_yes']

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [68]:
nn=KNeighborsClassifier(n_neighbors=3)
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("ACCRACY",accuracy_score(y_test,y_pred))

ACCRACY 0.3333333333333333

In [69]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [1, 1]])

In [70]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [71]:
ACCURACY=(TN+TP)/(TP+TN+FP+FN)
ERRORRATE=FP+FN/TP+TN+FP+FN
SENSITIVITY=TP/TP+FN
SPACIFICITY=TN/TN+FP
print(ACCURACY)
print(ERRORRATE)
print(SENSITIVITY)
print(SPACIFICITY)

0.3333333333333333
4.0
2.0
nan

C:\Users\LJENG\AppData\Local\Temp\ipykernel_12312\1145362724.py:4: RuntimeWarning: invalid value encountered in scalar divide
  SPACIFICITY=TN/TN+FP