In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
df=pd.read_csv('insurance.csv')
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [5]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'expenses'], dtype='object')

In [10]:
df=pd.get_dummies(data=df,drop_first=True)
df

,age,bmi,children,expenses,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.9,0,16884.92,False,True,False,False,True
1,18,33.8,1,1725.55,True,False,False,True,False
2,28,33.0,3,4449.46,True,False,False,True,False
3,33,22.7,0,21984.47,True,False,True,False,False
4,32,28.9,0,3866.86,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,31.0,3,10600.55,True,False,True,False,False
1334,18,31.9,0,2205.98,False,False,False,False,False
1335,18,36.9,0,1629.83,False,False,False,True,False
1336,21,25.8,0,2007.95,False,False,False,False,True
1337,61,29.1,0,29141.36,False,True,True,False,False

In [11]:
df.columns

Index(['age', 'bmi', 'children', 'expenses', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [17]:
x=df[['age', 'bmi', 'children', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest']]
y=df['expenses']

In [21]:
test=[0.1,0.2,0.3,0.4,0.5]
T=[]
R=[]
MSE=[]
for i in test:
    for j in range(1,51):
        x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=j,test_size=i)
        a=LinearRegression()
        a.fit(x_train,y_train)
        y_pred=a.predict(x_test)
        MSE.append(mean_squared_error(y_test,y_pred))
        R.append(j)
        T.append(i)

In [22]:
Data={"test_size":T,"random_state":R,"MSE":MSE}
df=pd.DataFrame(Data)
df.head()

   test_size  random_state           MSE
0        0.1             1  4.309228e+07
1        0.1             2  3.389797e+07
2        0.1             3  3.951443e+07
3        0.1             4  3.988952e+07
4        0.1             5  3.123591e+07

In [26]:
df['MSE'].min()

25964185.138925117

In [27]:
df[df['MSE']==25964185.138925117]

    test_size  random_state           MSE
35        0.1            36  2.596419e+07