In [1]:
# For the given RealEstate csv, write a python program satisfying following tasks to demonstrate application of machine learning
# through multiple linear regression as follows –
# Given: -
# Dataset RealEstate.csv
# ML Library to be used scikit-learn
# Dependent variable 'Y house price of unit area'
# Independent variables 'X1 transaction date', 'X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of
# convenience stores', 'X5 latitude' and 'X6 longitude'
# 1. Import required libraries.
# 2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.
# 3. Remove ‘No’ column from the dataframe.
# 4. Check for any null values in features using appropriate method.
# 5. Create feature variables x and y as given above.
# 6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
# 7. Create and fit regression model using appropriate method.
# 8. Use testing set created in step 6 to find and print the prediction of the outcome.
# 9. Find and print coefficient and mean squared error of the regression model.

In [24]:
import pandas as pd
from sklearn.metrics import mean_squared_error,r2_score,confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
df=pd.read_csv("RealEstate.csv")
df

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [10]:
x=df[['X1 transaction date', 'X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]
y=df['Y house price of unit area']
df.isna().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [11]:
# 6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=110,test_size=0.3)

In [12]:
# 7. Create and fit regression model using appropriate method.
a=LinearRegression()
a.fit(x_train,y_train)

LinearRegression()

In [13]:
# 8. Use testing set created in step 6 to find and print the prediction of the outcome.
y_pred=a.predict(x_test)
y_pred

array([40.06913335, 32.56470479, 29.80668902, 44.60809493, 39.96541473,
       44.34984726, 37.64834639, 51.18801909, 37.08044432, 38.64449437,
       36.45757424, 31.64776451, 43.03392987, 16.64984039, 36.61381207,
       31.21699197, 39.55333345, 41.89770923, 46.41953538, 42.69067202,
       40.49560609, 53.3447345 , 40.74436408, 36.67049204, 46.86499408,
       42.78349352, 47.25115307, 40.53653503, 42.57499139, 50.88772177,
       44.81813044, 41.05114011, 35.39386877, 42.95199941, 13.97578058,
       30.00463214,  0.32863779, 39.56884707, 47.9626967 , 34.0147913 ,
       40.23322474, 49.74492584, 36.73990519, 35.39784888, 29.6071314 ,
       45.83432319, 42.44745248, 37.88237609, 31.55675944, 47.517238  ,
       35.03089266, 45.17666152, 45.98711652, 47.32685806, 54.18178829,
       15.18888047, 43.78264851, 44.75385635, 37.69057227, 39.34215811,
       44.21812376, 44.27270068, 47.84570949, 38.42626454, 41.0626191 ,
       19.64522484, 47.9626967 , 43.85961508, 37.99756745, 43.80152052,
       42.39390912, 42.57768877, 44.73329588, 32.31758114, 46.89135756,
       38.92015239, 40.90438603, 43.95669962, 34.28075691, 25.5851042 ,
       16.26403643, 45.66098257, 42.05300968, 10.81561309, 31.65043887,
       49.10789869, 47.40016786, 13.5604683 , 46.02203009, 44.82145569,
       34.76747867, 35.40469328, 31.48202917, 45.59192922, 42.0246353 ,
       42.54274755, 14.70678074, 43.68554348, 27.69149444, 43.0460661 ,
       27.63908623, 35.23545719, 45.89665228, 50.31290226, 42.86214486,
       44.61671482, 49.59887911, 32.11577476, 31.86965512, 38.39003281,
       44.58865137, 25.50284004, 46.20113858, 37.45131001, 14.70678074,
       44.2357441 ,  9.25548578, 37.23816575, 38.97851394, 47.40016786,
       39.50115693, 32.15412829, 46.99435489, 47.07907957, 53.12308545])

In [19]:
print("Coeff",a.coef_)

Coeff [ 6.84308941e+00 -2.25466590e-01 -5.18046265e-03  1.12369103e+00
  1.87739728e+02 -4.29300312e+01]

In [20]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 77.14802598253651

In [25]:
print(df.dtypes)

No                                          int64
X1 transaction date                       float64
X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object

In [26]:
df.drop(columns="No")

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9