In [26]:
# Write a program to create a Model using linear regression to predict the charges of insurance using the csv file provided named
# “insurance.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and
# mean squared error.

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression

In [28]:
df=pd.read_csv("insurance.csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [30]:
df=pd.get_dummies(data=df,drop_first=True)
df

,age,bmi,children,expenses,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.9,0,16884.92,False,True,False,False,True
1,18,33.8,1,1725.55,True,False,False,True,False
2,28,33.0,3,4449.46,True,False,False,True,False
3,33,22.7,0,21984.47,True,False,True,False,False
4,32,28.9,0,3866.86,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,31.0,3,10600.55,True,False,True,False,False
1334,18,31.9,0,2205.98,False,False,False,False,False
1335,18,36.9,0,1629.83,False,False,False,True,False
1336,21,25.8,0,2007.95,False,False,False,False,True
1337,61,29.1,0,29141.36,False,True,True,False,False

In [33]:
x=df[['expenses']]
y=df['smoker_yes']

In [34]:
a=LinearRegression()

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [36]:
a.fit(x_train,y_train)

LinearRegression()

In [37]:
y_pred=a.predict(x_test)

In [38]:
print("MSE:", mean_squared_error(y_test,y_pred))

MSE: 0.05384162694590604

In [39]:
print(a.coef_)

[2.62411388e-05]

In [40]:
print(a.intercept_)

-0.14460911940872848

In [ ]:
15,16,17,20,21,23,30