In [1]:
# You have been provided with a dataset named students_performance.csv, which contains various features related to students' 
# performance in exams. The dataset includes features such as gender, race/ethnicity, parental level of education, lunch, test 
# preparation course, and scores in math, reading, and writing. Your task is to perform classification to predict whether a student 
# will pass or fail based on these features.
# Steps to complete:
#  1.Load the Dataset:
#  oLoad the dataset students_performance.csv into a pandas DataFrame.
#  oDisplay the first few rows to understand the structure of the dataset and check the sta s cs.
#  2.Preprocessing:
#  oConvert the scores in math, reading, and wri ng to a binary pass/fail label. Consider a score of 50 or above as pass(1) and 
# below 50 as fail(0).
#  oDrop the scores in math, reading, and wri ng.
#  oCreate a new Column named ‘Overall_Pass’ and create a binary label: pass(1) if Student passes all heads (math, reading, and 
# writing) and fail(0) if student has failed in even one head.
#  oEncode categorical variables (gender, race/ethnicity, parental level of educa on, lunch, test prepara on course) using one
# hot encoding.
#  oHandle any missing values if present.
#  oSplit the dataset into features (x) and target (y) where the target is the pass/fail label for the math pass.
#  oSplit the data into training (80%) sets using random state 10.

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [33]:
df = pd.read_csv("StudentsPerformance.csv")

In [34]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [35]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [36]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [38]:
math_pass=[]

In [39]:
for score in df['math score']:
    if score >= 50:
        math_pass.append(1)
    else:
        math_pass.append(0)
df['Math_Pass'] = math_pass

In [40]:
reading_pass = []
for score in df['reading score']:
    if score >= 50:
        reading_pass.append(1)
    else:
        reading_pass.append(0)
df['Reading_Pass'] = reading_pass

In [41]:
writing_pass = []
for score in df['writing score']:
    if score >= 50:
        writing_pass.append(1)
    else:
        writing_pass.append(0)
df['Writing_Pass'] = writing_pass

In [42]:
df['Overall_Pass'] = df.apply(lambda row: 1 
                              if (row['Math_Pass'] == 1 and 
                                  row['Reading_Pass'] == 1 and 
                                  row['Writing_Pass'] == 1) else 0, axis=1)

In [43]:
df.drop(['math score', 'reading score', 'writing score'], axis=1, inplace=True)

In [44]:
category=['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

In [45]:
df=pd.get_dummies(df, columns=category,drop_first=True)

In [46]:
df.isna().sum()

Math_Pass                                        0
Reading_Pass                                     0
Writing_Pass                                     0
Overall_Pass                                     0
gender_male                                      0
race/ethnicity_group B                           0
race/ethnicity_group C                           0
race/ethnicity_group D                           0
race/ethnicity_group E                           0
parental level of education_bachelor's degree    0
parental level of education_high school          0
parental level of education_master's degree      0
parental level of education_some college         0
parental level of education_some high school     0
lunch_standard                                   0
test preparation course_none                     0
dtype: int64

In [49]:
x=df.drop(['Math_Pass'], axis=1) 
y=df['Math_Pass']

In [50]:
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [51]:
x_train.shape

(800, 15)

In [52]:
x_test.shape

(200, 15)